{
 "title": "As Code Example - web_app.*",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "logsearch", "label": "Log Search String", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Application Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=~\"web_app.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Application Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=~\"web_app.*\"} |~ \"error\" [1m]))"
    }
   ]
  },
  {
   "title": "Application Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "quantile_over_time(0.95, {service_name=~\"web_app.*\"} | logfmt | unwrap duration(duration) | __error__=\"\" [$__interval]) by ()"
    }
   ]
  },
  {
   "title": "Raw Logs Search",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"web_app.*\"} | logfmt |~ \"$logsearch\" "
    }
   ]
  }
 ]
}